#!/bin/sh

# Ensure save directory exists
mkdir -p "${HOME}/.xsys35/saves/闘神都市２"

# cd to game directory and run xsystem35
HERE="$(dirname "$(readlink -f "${0}")")"
cd "${HERE}/usr/share/games/toushin2"
exec "${HERE}/usr/bin/xsystem35" "$@"
