#!/bin/sh

# Ensure save directory exists
mkdir -p "${HOME}/.xsys35/saves/学園KING"

# cd to game directory and run xsystem35
HERE="$(dirname "$(readlink -f "${0}")")"
export SDL_SOUNDFONTS="${HERE}/usr/share/games/gakuen/TimGM6mb.sf2"
cd "${HERE}/usr/share/games/gakuen"
exec "${HERE}/usr/bin/xsystem35" "$@"
