#!/bin/sh

# Ensure save directory exists
mkdir -p "${HOME}/.xsys35/saves/rance1"

# cd to game directory and run xsystem35
HERE="$(dirname "$(readlink -f "${0}")")"
export SDL_SOUNDFONTS="${HERE}/usr/share/games/rance1_en/TimGM6mb.sf2"
cd "${HERE}/usr/share/games/rance1_en"
exec "${HERE}/usr/bin/xsystem35" "$@"
